export const initialShiftPatterns = [
  { id: 'A', name: 'A', startTime: '9:00', endTime: '18:00', breakHours: 1.0, workHours: 8.0, displayTime: '9:00 - 18:00' },
  { id: 'B', name: 'B', startTime: '9:00', endTime: '17:30', breakHours: 1.0, workHours: 7.5, displayTime: '9:00 - 17:30' },
  { id: 'C', name: 'C', startTime: '9:00', endTime: '17:00', breakHours: 1.0, workHours: 7.0, displayTime: '9:00 - 17:00' },
  { id: 'D', name: 'D', startTime: '9:00', endTime: '16:30', breakHours: 1.0, workHours: 6.5, displayTime: '9:00 - 16:30' },
  { id: 'E', name: 'E', startTime: '9:00', endTime: '16:00', breakHours: 1.0, workHours: 6.0, displayTime: '9:00 - 16:00' },
  { id: 'F', name: 'F', startTime: '9:00', endTime: '15:30', breakHours: 1.0, workHours: 5.5, displayTime: '9:00 - 15:30' },
  { id: 'G', name: 'G', startTime: '9:00', endTime: '15:00', breakHours: 1.0, workHours: 5.0, displayTime: '9:00 - 15:00' },
  { id: 'H', name: 'H', startTime: '9:00', endTime: '13:00', breakHours: 0.0, workHours: 4.0, displayTime: '9:00 - 13:00' },
  { id: 'I', name: 'I', startTime: '9:30', endTime: '18:30', breakHours: 1.0, workHours: 8.0, displayTime: '9:30 - 18:30' },
  { id: 'J', name: 'J', startTime: '9:30', endTime: '18:00', breakHours: 1.0, workHours: 7.5, displayTime: '9:30 - 18:00' },
  { id: 'K', name: 'K', startTime: '9:30', endTime: '17:30', breakHours: 1.0, workHours: 7.0, displayTime: '9:30 - 17:30' },
  { id: 'L', name: 'L', startTime: '9:30', endTime: '17:00', breakHours: 1.0, workHours: 6.5, displayTime: '9:30 - 17:00' },
  { id: 'M', name: 'M', startTime: '9:30', endTime: '16:30', breakHours: 1.0, workHours: 6.0, displayTime: '9:30 - 16:30' },
  { id: 'N', name: 'N', startTime: '9:30', endTime: '16:00', breakHours: 1.0, workHours: 5.5, displayTime: '9:30 - 16:00' },
  { id: 'O', name: 'O', startTime: '9:30', endTime: '15:30', breakHours: 1.0, workHours: 5.0, displayTime: '9:30 - 15:30' },
  { id: 'P', name: 'P', startTime: '10:00', endTime: '18:30', breakHours: 1.0, workHours: 7.5, displayTime: '10:00 - 18:30' },
  { id: 'Q', name: 'Q', startTime: '10:00', endTime: '18:00', breakHours: 1.0, workHours: 7.0, displayTime: '10:00 - 18:00' },
  { id: 'R', name: 'R', startTime: '10:00', endTime: '17:00', breakHours: 1.0, workHours: 6.0, displayTime: '10:00 - 17:00' },
  { id: 'S', name: 'S', startTime: '10:00', endTime: '16:00', breakHours: 1.0, workHours: 5.0, displayTime: '10:00 - 16:00' },
  { id: 'T', name: 'T', startTime: '11:00', endTime: '20:00', breakHours: 1.0, workHours: 8.0, displayTime: '11:00 - 20:00' },
  { id: 'U', name: 'U', startTime: '13:00', endTime: '20:00', breakHours: 1.0, workHours: 6.0, displayTime: '13:00 - 20:00' },
  { id: 'V', name: 'V', startTime: '12:00', endTime: '20:00', breakHours: 1.0, workHours: 7.0, displayTime: '12:00 - 20:00' },
  { id: 'W', name: 'W', startTime: '13:30', endTime: '18:00', breakHours: 0.0, workHours: 4.5, displayTime: '13:30 - 18:00' },
  { id: 'X', name: 'X', startTime: '10:00', endTime: '14:00', breakHours: 0.0, workHours: 4.0, displayTime: '10:00 - 14:00' },
  { id: 'Y', name: 'Y', startTime: '10:00', endTime: '13:00', breakHours: 0.0, workHours: 3.0, displayTime: '10:00 - 13:00' },
  { id: 'Z', name: 'Z', startTime: '14:00', endTime: '20:00', breakHours: 1.0, workHours: 5.0, displayTime: '14:00 - 20:00' },
  { id: '@', name: '@', startTime: '14:30', endTime: '20:00', breakHours: 1.0, workHours: 4.5, displayTime: '14:30 - 20:00' },
];

export const initialStaffData = [
  { id: 's1', employeeId: 'DG00000009', name: '坂下祐介', role: 'OP', pin: '1111', chatUserId: '', possibleTasks: ['t1', 't3'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's2', employeeId: 'DG00000011', name: '大﨑楽忠', role: 'OP', pin: '1112', chatUserId: '', possibleTasks: ['t2', 't4'], defaultShift: { pattern: ['I', 'I', 'I', 'I', 'I'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's3', employeeId: 'DG00000029', name: '山下大空', role: 'OP', pin: '1113', chatUserId: '', possibleTasks: ['t1', 't2'], defaultShift: { pattern: ['I', 'I', 'I', 'I', 'I'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's4', employeeId: 'DG00000027', name: '中村有志', role: 'OP', pin: '1114', chatUserId: '', possibleTasks: ['t3', 't4'], defaultShift: { pattern: ['I', 'I', 'I', 'I', 'I'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's5', employeeId: 'DG00000036', name: '渡部翔太', role: 'OP', pin: '1115', chatUserId: '', possibleTasks: ['t1', 't4', 't5'], defaultShift: { pattern: ['K', 'K', 'K', 'K', 'K'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's6', employeeId: 'DG00000025', name: '佐々木由基', role: 'OP', pin: '1116', chatUserId: '', possibleTasks: ['t2', 't3', 't6'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's7', employeeId: 'DG00000020', name: '江岸恭平', role: 'OP', pin: '1117', chatUserId: '', possibleTasks: ['t1', 't7'], defaultShift: { pattern: ['I', 'I', 'I', 'I', 'I'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's8', employeeId: 'DG00000018', name: '池田学司', role: 'OP', pin: '1118', chatUserId: '', possibleTasks: ['t2', 't8'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's9', employeeId: 'OP51', name: '加藤清史郎', role: 'OP', pin: '1119', chatUserId: '', possibleTasks: ['t3', 't9'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's10', employeeId: 'OP52', name: '吉田羊', role: 'OP', pin: '1120', chatUserId: '', possibleTasks: ['t4', 't10'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's11', employeeId: 'OP53', name: '斎藤工', role: 'OP', pin: '1121', chatUserId: '', possibleTasks: ['t1', 't2', 't3', 't11'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's12', employeeId: 'OP54', name: '木村佳乃', role: 'OP', pin: '1122', chatUserId: '', possibleTasks: ['t4', 't1', 't12'], defaultShift: { pattern: ['H', 'H', 'H', 'H', 'H'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's13', employeeId: 'OP55', name: '山田孝之', role: 'OP', pin: '1123', chatUserId: '', possibleTasks: ['t2', 't3', 't13'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's14', employeeId: 'OP56', name: '井上真央', role: 'OP', pin: '1124', chatUserId: '', possibleTasks: ['t1', 't4', 't14'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's15', employeeId: 'OP57', name: '松本潤', role: 'OP', pin: '1125', chatUserId: '', possibleTasks: ['t2', 't15'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's16', employeeId: 'OP58', name: '長澤まさみ', role: 'OP', pin: '1126', chatUserId: '', possibleTasks: ['t3', 't16'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's17', employeeId: 'OP59', name: '岡田准一', role: 'OP', pin: '1234', chatUserId: '', possibleTasks: ['t4', 't17'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's18', employeeId: 'OP60', name: '綾瀬はるか', role: 'OP', pin: '5678', chatUserId: '', possibleTasks: ['t1', 't18'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's19', employeeId: 'OP61', name: '小栗旬', role: 'OP', pin: '1127', chatUserId: '', possibleTasks: ['t2', 't4', 't19'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's20', employeeId: 'OP62', name: '石原さとみ', role: 'OP', pin: '1128', chatUserId: '', possibleTasks: ['t3', 't1'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's21', employeeId: 'OP63', name: '藤原竜也', role: 'OP', pin: '1129', chatUserId: '', possibleTasks: ['t1', 't2'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's22', employeeId: 'OP64', name: '北川景子', role: 'OP', pin: '1130', chatUserId: '', possibleTasks: ['t3', 't4'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's23', employeeId: 'OP65', name: '香川照之', role: 'OP', pin: '1131', chatUserId: '', possibleTasks: ['t1', 't3'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's24', employeeId: 'OP66', name: '満島ひかり', role: 'OP', pin: '1132', chatUserId: '', possibleTasks: ['t2', 't4'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's25', employeeId: 'OP67', name: '堺雅人', role: 'OP', pin: '1133', chatUserId: '', possibleTasks: ['t1', 't5'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's26', employeeId: 'OP68', name: '柴咲コウ', role: 'OP', pin: '1134', chatUserId: '', possibleTasks: ['t2', 't6'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's27', employeeId: 'OP69', name: '阿部寛', role: 'OP', pin: '1135', chatUserId: '', possibleTasks: ['t3', 't7'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's28', employeeId: 'OP70', name: '竹内結子', role: 'OP', pin: '1136', chatUserId: '', possibleTasks: ['t4', 't8'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's29', employeeId: 'OP71', name: '役所広司', role: 'OP', pin: '1137', chatUserId: '', possibleTasks: ['t1', 't2', 't4', 't9'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
  { id: 's30', employeeId: 'OP72', name: '天海祐希', role: 'OP', pin: '1138', chatUserId: '', possibleTasks: ['t3', 't2', 't10'], defaultShift: { pattern: ['A', 'A', 'A', 'A', 'A'] }, shiftSubmitted: {}, shiftRemanded: {}, shiftApproved: {} },
];

export const initialAdminConfig = {
  submissionNotificationIds: "103447655031837803879, 104076674700109610671"
};

export const initialTasks = [
  { id: 't1', name: '早番電話', requiredPersonnel: 3 },
  { id: 't2', name: '遅番電話', requiredPersonnel: 3 },
  { id: 't3', name: 'メール対応', requiredPersonnel: 2 },
  { id: 't4', name: 'チャット対応', requiredPersonnel: 2 },
];
